// The Party Mode green-card deck — its own deck, separate from the weekly
// queue in Supabase, so game night never spoils (or drains) the cards
// Stephen has lined up for the town. House style, same as
// data/green-cards.md: specific, warm, and locally knowing. Punch at
// potholes, construction season, and winter — never at people or
// businesses.

export const PARTY_CARDS = [
  'The most Vermont thing you can do before 7 a.m.',
  'What Champ is really hiding from us',
  "Burlington's next official town holiday",
  'The secret ingredient in a proper maple creemee',
  'The true reason the bike path curves right there',
  'A perfectly Vermont excuse for missing work',
  'What flatlanders will simply never understand',
  "The next big Church Street street performer act",
  "What's actually at the bottom of Lake Champlain",
  "Vermont's real state motto",
  'The one thing every Burlington apartment has',
  'What the waterfront geese are arguing about',
  'The unwritten rule of the farmers market',
  "Winter's only redeeming quality",
  'What mud season smells like',
  'The most romantic spot in Chittenden County',
  "A Vermonter's idea of dressing up",
  'The best thing to yell when jumping into the lake',
  'What the foliage is whispering to the leaf peepers',
  'The eighth season of Vermont weather',
  'What really lives in the steam tunnels under UVM',
  'The next thing Burlington will put maple in',
  'A completely normal sight on the bike path',
  'What the Adirondacks think of us from across the lake',
  'The real reason the ferry is running late',
  'The town meeting agenda item that takes three hours',
  "Champ's day job in the off-season",
  'The Vermontiest possible wedding',
  'What the snowplow drivers talk about at 4 a.m.',
  'The last thing you want to hear on a chairlift',
  'The first sign that spring has truly arrived',
  'What Burlington dogs gossip about at the dog park',
  'The perfect fourth ingredient for a maple creemee sundae',
  "The pothole on your street's secret ambition",
  'What construction season is actually building',
  'A Vermont superpower nobody asked for',
  'The most passive-aggressive thing you can do with a front porch',
  'What the church bells downtown are really announcing',
  'The next craze to sweep the co-op parking lot',
  'The polite Vermont way to end a conversation that will not end',
  'What sugarmakers dream about in February',
  'The wildest thing ever traded at a Vermont swap meet',
  'The real reason the interstate exit numbers make no sense',
  'What the lake is thinking during stick season',
  'A Green Mountain ghost story in five words or less',
  'The item every Vermont junk drawer is legally required to contain',
  'What you can smell from the top of Mount Philo',
  'The truth about where the bike path actually goes',
  'The next thing Vermont should put on a license plate',
  'The most Vermont way to win an argument',
  'What the snowbanks know but will not tell',
  'The secret handshake of people who stay all winter',
];
